"""Add order_index column to Task model

Revision ID: 0715111cf333
Revises: 296135b5a7ef
Create Date: 2024-04-28 23:30:41.216042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0715111cf333'
down_revision = '296135b5a7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('order_index')

    # ### end Alembic commands ###
