"""changed name from ordered index to AI Arranged

Revision ID: 0b60ec18d23b
Revises: 0715111cf333
Create Date: 2024-04-29 10:48:09.710232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b60ec18d23b'
down_revision = '0715111cf333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AI_Arranged', sa.Integer(), nullable=False))
        batch_op.drop_column('order_index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('AI_Arranged')

    # ### end Alembic commands ###
